### ISSUE TITLE
If I don't specify default response, I get a TS error on endpoint request

### ISSUE THREAD

**Issue by hukus** [SamWSoftware/serverless-auto-swagger#16]
If I don't specify default response, I get a TS error on endpoint request. The error says following:
```
TypeError: Cannot destructure property 'responseParameters' of 'chosenResponse' as it is undefined.
```
If I add `default` response, it works. 
This is probably not desired, as 200 should be automatically the default response.
I traced the problem to `serverless-offline` package, specifically to `HttpServer.js` file where the responses are parsed.

EXAMPLES
Settings that are cause error:
```
    events:
      - http:
          method: get
          path: /transports
          cors:
            origin: '*'
            headers: '*'
          responses: 
            200:
              description: 'List of possible transport options'
              bodyType: 'TransportsResponseType'
            400:
              bodyType: 'GeneralErrorType'
```

Settings that work OK:
```
    events:
      - http:
          method: get
          path: /transports
          cors:
            origin: '*'
            headers: '*'
          responses: 
            default: 
              description: 'Use this endpoint to list possible options for transport of material and parts'
            200:
              description: 'List of possible transport options'
              bodyType: 'TransportsResponseType'
            400:
              bodyType: 'GeneralErrorType'
```

**Comment by desaintvincent** [comment]
I had the same issue, traced, conclude and fixed it the same way. Maybe this serverless-auto-swagger can add default to the first response (would be 200 in your case) if there is not already one?

This solution feels like a dirty piece of tape.

On the other hand, is it serverless-auto-swagger's responsability to do that?

An other solution could be to use something like `swaggerResponse` instead of `response`, but that would cause breaking change...

I can do the PR if you want, but we should find a smart solution that @SamWSoftware agrees with

**Comment by desaintvincent** [comment]
thanks @bfaulk96 ! I think we can now close this issue
