### ISSUE TITLE
Any way to add descriptions for query params and model properties ?

### ISSUE THREAD

**Issue by the-dext** [SamWSoftware/serverless-auto-swagger#2]
Thanks for creating this serverless plugin, I've found it really useful.

Is there a way to document query string parameters and provide descriptions on model properties ?

**Comment by SamWSoftware** [comment]
Not yet. That was going to be the next feature.

**Comment by SamWSoftware** [comment]
This has recent;y been added

**Comment by jguerinet** [comment]
@SamWSoftware I see the documentation options for the query string parameters, is there a way to provide descriptions on the model properties? 
When looking at my models, I see that if I put a comment in `/** */` at the type level it gets parsed to be the description of the model. But if I put comments at the property level it doesn't get added as description for the property (all I see is `title: ModelName.propertyName` under the property type). Is there a way to add this with the current version of `serverless-auto-swagger`?

**Comment by bfaulk96** [comment]
@jguerinet We're using `typeconv` to convert TS to JSON Schema, so this is likely out of the scope of what we can accomplish, although I haven't had time to look into improving types.

**Comment by jguerinet** [comment]
I dug a bit in `typeconv` and you can actually do this with the following syntax: 
```
export type Object = {
    /** This will generate a description for the field */
    field: string;
};
```

Here's the result: 
<img width="526" alt="Screen Shot 2022-07-14 at 20 19 26" src="https://user-images.githubusercontent.com/5423145/179122206-5cda9b7c-9b2c-4a72-b2d7-34600f511f38.png">

No way to remove the `title` field unfortunately, I find it a bit redundant but `typeconv` keeps it by default. The issue was discussed [here](https://github.com/grantila/typeconv/issues/13), I have asked to see if it's something they would consider adding.

**Comment by chelodegli** [comment]
Is there a way to add "example" value in queryStringParameters?

I tried a few ways but didn't work, not sure if it's an actual feature.

I'm thinking something like this:
```
queryStringParameters: {
                  limit: {
                      required: false,
                      type: 'integer',
                      description: 'Maximum amount of registers to query',
                      _**example: '25',**_
                  }
```
