### ISSUE TITLE
Outdated NPM Docs. It still says to use "responses" instead of "responseData"

### ISSUE THREAD

**Issue by alanschapira** [SamWSoftware/serverless-auto-swagger#68]
The npm docs say that response body is:

```
responses: {
    // response with description and response body
    200: {
        description: 'this went well',
        bodyType: 'helloPostResponse',
    },

    // response with just a description
    400: {
        description: 'failed Post',
    },
    // shorthand for just a description
    502: 'server error',
}
```

whereas the docs on github says response body is:

```
responseData: {
    // response with description and response body
    200: {
        description: 'this went well',
        bodyType: 'helloPostResponse',
    },

    // response with just a description
    400: {
        description: 'failed Post',
    },
    // shorthand for just a description
    502: 'server error',
}
```

Also the youtube video you posted has the old way. Might be worth putting something in there too. https://www.youtube.com/watch?v=vkTIM9MQ5Wc

**Comment by bfaulk96** [comment]
I believe the docs are now up-to-date in NPM. As for the YouTube video, a lot has changed since the first was recorded, I agree. I'm not sure why, but it appears that NPM doesn't automatically update the docs when we push for some reason, I think Sam has to update them manually.

Going to go ahead and close this now though since 2.4.1 is reflected [in NPM](https://www.npmjs.com/package/serverless-auto-swagger)
